added invoking issues for policy failure

diff --git a/.github/workflows/kyverno-policy-test.yml b/.github/workflows/kyverno-policy-test.yml
--- a/.github/workflows/kyverno-policy-test.yml
+++ b/.github/workflows/kyverno-policy-test.yml
@@ -24,3 +24,21 @@ jobs:
 
       - name: Test the policy against the resource
         run: kyverno apply policies/cpol-disallow-default-namespace.yml --resource manifests/bad_pod.yml --table
+
+      - name: Check policy validation status & raise an issue
+        run: |
+          exitcode="$?"
+          echo "exitcode==$exitcode"
+          if [[ exitcode == "1" ]]; then
+            echo "Policy validation failed, creating an issue."
+            curl -L \
+            -X POST \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            https://api.github.com/repos/cerebro1/kyverno/issues \
+            -d '{"title":"Kyverno Policy Validation Failed.","body":"Policy cpol-disallow-default-namespace failed."}'
+          else
+             echo "Policy validation successfull."
+            exit 0
+          fi
